// <auto-generated />
using System;
using ETicaretAPI.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ETicaretAPI.Persistence.Migrations
{
    [DbContext(typeof(ETicaretAPIDbDontext))]
    [Migration("20240310154209_mig_1")]
    partial class mig_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ETicaretAPI.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4f8fa92-fd1a-404e-b91a-9a1bee8c23fb"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7325),
                            Name = "Faruk",
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7326)
                        },
                        new
                        {
                            Id = new Guid("37385c93-2835-4059-9a44-09f881a48753"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7327),
                            Name = "Aslan",
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7327)
                        });
                });

            modelBuilder.Entity("ETicaretAPI.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a6457d8-e475-45f4-9ced-bb8d009f4a5d"),
                            Address = "Eraykent",
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7375),
                            CustomerId = new Guid("b4f8fa92-fd1a-404e-b91a-9a1bee8c23fb"),
                            Description = "Customer b4f8fa92-fd1a-404e-b91a-9a1bee8c23fb",
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7375)
                        },
                        new
                        {
                            Id = new Guid("c399b3c5-e7ae-4e81-b560-b3e67966efd0"),
                            Address = "Maltepe",
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7379),
                            CustomerId = new Guid("b4f8fa92-fd1a-404e-b91a-9a1bee8c23fb"),
                            Description = "Customer b4f8fa92-fd1a-404e-b91a-9a1bee8c23fb",
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7380)
                        },
                        new
                        {
                            Id = new Guid("317f7226-e8b4-42e5-8397-5c9421b0a3aa"),
                            Address = "Kartal",
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7384),
                            CustomerId = new Guid("37385c93-2835-4059-9a44-09f881a48753"),
                            Description = "Customer 37385c93-2835-4059-9a44-09f881a48753",
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7384)
                        });
                });

            modelBuilder.Entity("ETicaretAPI.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6646519c-01f5-434f-ad87-719e8d1e566a"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7139),
                            Name = "Product 1",
                            Price = 500f,
                            Stock = 100,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7141)
                        },
                        new
                        {
                            Id = new Guid("6e61ce0b-4cf3-4851-a81f-be772c3efec8"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7144),
                            Name = "Product 2",
                            Price = 600f,
                            Stock = 200,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7145)
                        },
                        new
                        {
                            Id = new Guid("7eeba2e4-e66f-4075-991f-c607d9f0b780"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7147),
                            Name = "Product 3",
                            Price = 700f,
                            Stock = 300,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7147)
                        },
                        new
                        {
                            Id = new Guid("b13fb4d5-2dc6-4407-87b1-7caee3b385ab"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7149),
                            Name = "Product 4",
                            Price = 800f,
                            Stock = 400,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7149)
                        },
                        new
                        {
                            Id = new Guid("0f573d19-f500-4484-aaea-9b17dd2e603f"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7151),
                            Name = "Product 5",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7151)
                        },
                        new
                        {
                            Id = new Guid("32980ca4-1b8f-43d2-91d8-ecdc13345f27"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7169),
                            Name = "Product 6",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7169)
                        },
                        new
                        {
                            Id = new Guid("4dfccbee-cabf-420e-98bd-c37793b9113c"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7171),
                            Name = "Product 7",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7172)
                        },
                        new
                        {
                            Id = new Guid("fc823166-4091-4ecd-9bf2-75f4005d7318"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7173),
                            Name = "Product 8",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7174)
                        },
                        new
                        {
                            Id = new Guid("6735926e-a024-44e4-892a-3fc8b186639f"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7175),
                            Name = "Product 9",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7176)
                        },
                        new
                        {
                            Id = new Guid("b1f2ad85-4c3f-4112-abd2-573ad34ce58a"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7177),
                            Name = "Product 10",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7178)
                        },
                        new
                        {
                            Id = new Guid("a8fe1daa-2697-4956-8761-62dde0b29865"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7179),
                            Name = "Product 11",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7180)
                        },
                        new
                        {
                            Id = new Guid("412a41d6-1d65-43dd-a8a7-57817b860d67"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7181),
                            Name = "Product 12",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7182)
                        },
                        new
                        {
                            Id = new Guid("55892398-5bca-4e10-81bf-eb2f756d034e"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7183),
                            Name = "Product 13",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7184)
                        },
                        new
                        {
                            Id = new Guid("ae9b44fa-4584-4797-86bf-5672c116cdc7"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7188),
                            Name = "Product 14",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7189)
                        },
                        new
                        {
                            Id = new Guid("621351df-3c01-43ac-b6cd-301edf40325b"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7190),
                            Name = "Product 15",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7191)
                        },
                        new
                        {
                            Id = new Guid("265683a3-aa38-4566-8672-a04026ad722a"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7192),
                            Name = "Product 16",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7193)
                        },
                        new
                        {
                            Id = new Guid("a8092878-6f14-4514-96a0-6201a6a1661a"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7194),
                            Name = "Product 17",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7195)
                        },
                        new
                        {
                            Id = new Guid("eec2add7-75ac-4d17-ae34-b668645459be"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7196),
                            Name = "Product 18",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7197)
                        },
                        new
                        {
                            Id = new Guid("0f76ed9c-16bb-4589-82fb-8cba14f54cc3"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7198),
                            Name = "Product 19",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7199)
                        },
                        new
                        {
                            Id = new Guid("54b880e0-584d-448e-b004-6cf245d31f44"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7200),
                            Name = "Product 5",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7201)
                        },
                        new
                        {
                            Id = new Guid("8dba5805-e09d-4c21-bb6f-5d612256f557"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7202),
                            Name = "Product 5",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7203)
                        },
                        new
                        {
                            Id = new Guid("c321c1d8-6de4-4baa-823e-0fe37f467080"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7207),
                            Name = "Product 5",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7207)
                        },
                        new
                        {
                            Id = new Guid("cc55152b-6f4b-4284-adac-9e0e1ab37a1c"),
                            CreatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7209),
                            Name = "Product 5",
                            Price = 900f,
                            Stock = 500,
                            UpdatedTime = new DateTime(2024, 3, 10, 15, 42, 9, 640, DateTimeKind.Utc).AddTicks(7209)
                        });
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<Guid>("OrdersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uuid");

                    b.HasKey("OrdersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("ETicaretAPI.Domain.Entities.Order", b =>
                {
                    b.HasOne("ETicaretAPI.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("ETicaretAPI.Domain.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ETicaretAPI.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ETicaretAPI.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
